repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: go-fmt
    - id: go-vet
      language: system
      entry: bash -c 'cd services/product && go vet'
    - id: go-imports
    - id: validate-toml
    - id: no-go-testing
    - id: go-mod-tidy